function get_linker_option_info()
    return {
        {option="--abi", description="Specifies which data model to link for"},
        {option="--accurate_math", description="Uses more accurate math functions"},
        {option="--advanced_heap", description="Uses an advanced heap"},
        {option="--basic_heap", description="Uses a basic heap"},
        {option="--BE8", description="Uses the big-endian format BE8"},
        {option="--BE32", description="Uses the big-endian format BE32"},
        {option="--bounds_table_size", description="Specifies the size of the global bounds table"},
        {option="--call_graph", description="Produces a call graph file in XML format"},
        {option="--config", description="Specifies the linker configuration file to be used by the linker"},
        {option="--config_def", description="Defines symbols for the configuration file"},
        {option="--config_search", description="Specifies more directories to search for linker configuration files"},
        {option="--cpp_init_routine", description="Specifies a user-defined C++ dynamic initialization routine"},
        {option="--cpu", description="Specifies a processor variant"},
        {option="--debug_heap", description="Uses the checked heap"},
        {option="--default_to_complex_ranges", description="Makes complex ranges the default decompressor in initialize directives"},
        {option="--define_symbol", description="Defines symbols that can be used by the application"},
        {option="--dependencies", description="Lists file dependencies"},
        {option="--diag_error", description="Treats these message tags as errors"},
        {option="--diag_remark", description="Treats these message tags as remarks"},
        {option="--diag_suppress", description="Suppresses these diagnostic messages"},
        {option="--diag_warning", description="Treats these message tags as warnings"},
        {option="--diagnostics_tables", description="Lists all diagnostic messages"},
        {option="--do_segment_pad", description="Pads each ELF segment to n-byte alignment"},
        {option="--enable_hardware_workaround", description="Enables specified hardware workaround"},
        {option="--enable_stack_usage", description="Enables stack usage analysis"},
        {option="--entry", description="Treats the symbol as a root symbol and as the start of the application"},
        {option="--entry_list_in_address_order", description="Generates an additional entry list in the map file sorted in address order"},
        {option="--error_limit", description="Specifies the allowed number of errors before linking stops"},
        {option="--exception_tables", description="Generates exception tables for C code"},
        {option="--export_builtin_config", description="Produces an icf file for the default configuration"},
        {option="--extra_init", description="Specifies an extra initialization routine that will be called if it is defined"},
        {option="-f", description="Extends the command line"},
        {option="--f", description="Extends the command line, optionally with a dependency"},
        {option="--force_exceptions", description="Always includes exception runtime code"},
        {option="--force_output", description="Produces an output file even if errors occurred"},
        {option="--fpu", description="Selects the FPU to link your application for"},
        {option="--ignore_uninstrumented_pointers", description="Disables checking of accessing via pointers in memory for which no bounds have been set"},
        {option="--image_input", description="Puts an image file in a section"},
        {option="--import_cmse_lib_in", description="Reads previous version of import library for building a non-secure image"},
        {option="--import_cmse_lib_out", description="Produces an import library, for building a non-secure image"},
        {option="--inline", description="Inlines small routines"},
        {option="--keep", description="Forces a symbol to be included in the application"},
        {option="-L", description="Specifies more directories to search for object and library files. Alias for --search"},
        {option="--library_security", description="Forces the linker to select a runtime library with or without support for PACBTI"},
        {option="--log", description="Enables log output for selected topics"},
        {option="--log_file", description="Directs the log to a file"},
        {option="--mangled_names_in_messages", description="Adds mangled names in messages"},
        {option="--manual_dynamic_initialization", description="Suppresses automatic initialization during system startup"},
        {option="--map", description="Produces a map file"},
        {option="--merge_duplicate_sections", description="Merges equivalent read-only sections"},
        {option="--no_bom", description="Omits the Byte Order Mark from UTF-8 output files"},
        {option="--no_dynamic_rtti_elimination", description="Includes dynamic runtime type information even when it is not needed"},
        {option="--no_entry", description="Sets the entry point to zero"},
        {option="--no_exceptions", description="Generates an error if exceptions are used"},
        {option="--no_fragments", description="Disables section fragment handling"},
        {option="--no_free_heap", description="Uses the smallest possible heap implementation"},
        {option="--no_inline", description="Excludes functions from small function inlining"},
        {option="--no_library_search", description="Disables automatic runtime library search"},
        {option="--no_literal_pool", description="Generates code that should run from a memory region where it is not allowed to read data, only to execute code"},
        {option="--no_locals", description="Removes local symbols from the ELF executable image"},
        {option="--no_range_reservations", description="Disables range reservations for absolute symbols"},
        {option="--no_remove", description="Disables removal of unused sections"},
        {option="--no_vfe", description="Disables Virtual Function Elimination"},
        {option="--no_warnings", description="Disables generation of warnings"},
        {option="--no_wrap_diagnostics", description="Does not wrap long lines in diagnostic messages"},
        {option="-o", description="Alias for --output"},
        {option="--only_stdout", description="Uses standard output only"},
        {option="--output", description="Sets the object filename"},
        {option="--pi_veneers", description="Generates position independent veneers"},
        {option="--place_holder", description="Reserve a place in ROM to be filled by some other tool, for example, a checksum calculated by ielftool"},
        {option="--preconfig", description="Reads the specified file before reading the linker configuration file"},
        {option="--printf_multibytes", description="Makes the printf formatter support multibytes"},
        {option="--redirect", description="Redirects a reference to a symbol to another symbol"},
        {option="--remarks", description="Enables remarks"},
        {option="--require_bti", description="Generate an error if modules do not have the same support for BTI"},
        {option="--require_pac", description="Generate a warning if modules do not have the same support for PAC"},
        {option="--scanf_multibytes", description="Makes the scanf formatter support multibytes"},
        {option="--search", description="Specifies more directories to search for object and library files"},
        {option="--semihosting", description="Links with debug interface"},
        {option="--silent", description="Sets silent operation"},
        {option="--small_math", description="Uses smaller math functions"},
        {option="--stack_usage_control", description="Specifies a stack usage control file"},
        {option="--strip", description="Removes debug information from the executable image"},
        {option="--text_out", description="Specifies the encoding for text output files"},
        {option="--threaded_lib", description="Configures the runtime library for use with threads"},
        {option="--timezone_lib", description="Enables the time zone and daylight savings time functionality in the library"},
        {option="--treat_rvct_modules_as_softf", description="Treats all modules generated by RVCT as using the standard (non-VFP) calling convention"},
        {option="--use_full_std_template_names", description="Enables full names for standard C++ templates"},
        {option="--use_optimized_variants", description="Controls the use of optimized variants of DLIB library functions"},
        {option="--utf8_text_in", description="Uses the UTF-8 encoding for text input files"},
        {option="--version", description="Sends version information to the console and then exits"},
        {option="--vfe", description="Controls Virtual Function Elimination"},
        {option="--warnings_affect_exit_code", description="Warnings affects exit code"},
        {option="--warnings_are_errors", description="Warnings are treated as errors"},
        {option="--whole_archive", description="Treats every object file in the archive as if it was specified on the command line"},
    }
end
